[package]
name = "docup"
version = "0.1.0"
edition = "2021"

[dependencies]
html = { version = "0.6.3", optional = true }
svg = { version = "0.15.1", optional = true }

[features]
default = ["md"]
html = ["dep:html"]
svg = ["dep:svg"]
md = []

